
@hostname = localhost
@port  = 8080
@host = {{hostname}}:{{port}}

###
// Log in to petclinic
# @name login
# @prompt username
# @prompt password
POST http://{{host}}/api/v1/auth/signin HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###
// Get pets by user id
GET http://{{host}}/api/v1/pets?userId={{login.response.body.$.id}} HTTP/1.1
Authorization: Bearer {{login.response.body.$.token}}
Pricing-Token: {{login.response.body.$.pricingToken}}
Accept: application/json


###
// Create a new pet
# @name createPet
# @prompt petName

POST http://{{host}}/api/v1/pets
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{login.response.body.$.token}}
Pricing-Token: {{login.response.body.$.pricingToken}}

{
    "id": null,
    "name": "{{petName}}",
    "birthDate": "2025-03-27",
    "type": {
        "id": 5,
        "name": "bird"
    },
    "owner": {}
}

###
# @name deletePet
@petId = {{createPet.response.body.$.id}}

DELETE  http://{{host}}/api/v1/pets/{{petId}}
Authorization: Bearer {{login.response.body.$.token}}
Pricing-Token: {{login.response.body.$.pricingToken}}

###
# @name getConsultations
// Get consultations of owner
GET http://{{host}}/api/v1/consultations HTTP/1.1
Accept: application/json
Authorization: Bearer {{login.response.body.$.token}}
Pricing-Token: {{login.response.body.$.pricingToken}}

###
# @name getConsultationById
// Get consultation by id
// Owner 1 Consultations Ids:
// 1, 2

@consultationId = {{getConsultations.response.body.$.[0].id}}

GET http://{{host}}/api/v1/consultations/{{consulationId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{login.response.body.$.token}}
Pricing-Token: {{login.response.body.$.pricingToken}}


###

POST http://{{host}}/api/v1/consultations HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}
Pricing-Token: {{login.response.body.$.pricingToken}}

{
   "id":null,
   "title": "What vaccines should my pet get?",
   "status": "PENDING",
   "isClinicComment": false,
   "pet": {{getConsultationById.response.body.$.pet}},
   "owner": {{getConsultationById.response.body.$.owner}}
}

###
@consultationId = {{getConsultations.response.body.$.[0].id}}


PUT http://{{host}}/api/v1/consultations/{{consultationId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}
Pricing-Token: {{login.response.body.$.pricingToken}}

{
   "id":null,
   "title": "What vaccines should my pet get?",
   "status": "PENDING",
   "isClinicComment": false,
   "pet": {{getConsultationById.response.body.$.pet}},
   "owner": {{getConsultationById.response.body.$.owner}}
}
