// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: featureResponse.proto

package org.springframework.samples.petclinic.protobuf;

public final class FeatureResponseOuterProto {
  private FeatureResponseOuterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FeatureResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FeatureResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
     */
    int getFeatureMapCount();
    /**
     * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
     */
    boolean containsFeatureMap(
        java.lang.String key);
    /**
     * Use {@link #getFeatureMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature>
    getFeatureMap();
    /**
     * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
     */
    java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature>
    getFeatureMapMap();
    /**
     * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
     */
    /* nullable */
FeatureResponseOuterProto.FeatureResponse.Feature getFeatureMapOrDefault(
        java.lang.String key,
        /* nullable */
FeatureResponseOuterProto.FeatureResponse.Feature defaultValue);
    /**
     * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
     */
    FeatureResponseOuterProto.FeatureResponse.Feature getFeatureMapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code FeatureResponse}
   */
  public static final class FeatureResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FeatureResponse)
      FeatureResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FeatureResponse.newBuilder() to construct.
    private FeatureResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FeatureResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FeatureResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FeatureResponseOuterProto.internal_static_FeatureResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetFeatureMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FeatureResponseOuterProto.internal_static_FeatureResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FeatureResponseOuterProto.FeatureResponse.class, FeatureResponseOuterProto.FeatureResponse.Builder.class);
    }

    public interface FeatureOrBuilder extends
        // @@protoc_insertion_point(interface_extends:FeatureResponse.Feature)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.FeatureResponse.Feature.ValueType valueType = 1;</code>
       * @return The enum numeric value on the wire for valueType.
       */
      int getValueTypeValue();
      /**
       * <code>.FeatureResponse.Feature.ValueType valueType = 1;</code>
       * @return The valueType.
       */
      FeatureResponseOuterProto.FeatureResponse.Feature.ValueType getValueType();

      /**
       * <code>bool booleanValue = 2;</code>
       * @return Whether the booleanValue field is set.
       */
      boolean hasBooleanValue();
      /**
       * <code>bool booleanValue = 2;</code>
       * @return The booleanValue.
       */
      boolean getBooleanValue();

      /**
       * <code>string stringValue = 3;</code>
       * @return Whether the stringValue field is set.
       */
      boolean hasStringValue();
      /**
       * <code>string stringValue = 3;</code>
       * @return The stringValue.
       */
      java.lang.String getStringValue();
      /**
       * <code>string stringValue = 3;</code>
       * @return The bytes for stringValue.
       */
      com.google.protobuf.ByteString
          getStringValueBytes();

      /**
       * <code>int32 numericValue = 4;</code>
       * @return Whether the numericValue field is set.
       */
      boolean hasNumericValue();
      /**
       * <code>int32 numericValue = 4;</code>
       * @return The numericValue.
       */
      int getNumericValue();

      public FeatureResponseOuterProto.FeatureResponse.Feature.ValueCase getValueCase();
    }
    /**
     * Protobuf type {@code FeatureResponse.Feature}
     */
    public static final class Feature extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:FeatureResponse.Feature)
        FeatureOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Feature.newBuilder() to construct.
      private Feature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Feature() {
        valueType_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Feature();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FeatureResponseOuterProto.internal_static_FeatureResponse_Feature_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FeatureResponseOuterProto.internal_static_FeatureResponse_Feature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FeatureResponseOuterProto.FeatureResponse.Feature.class, FeatureResponseOuterProto.FeatureResponse.Feature.Builder.class);
      }

      /**
       * Protobuf enum {@code FeatureResponse.Feature.ValueType}
       */
      public enum ValueType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>BOOLEAN = 0;</code>
         */
        BOOLEAN(0),
        /**
         * <code>STRING = 1;</code>
         */
        STRING(1),
        /**
         * <code>NUMERIC = 2;</code>
         */
        NUMERIC(2),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>BOOLEAN = 0;</code>
         */
        public static final int BOOLEAN_VALUE = 0;
        /**
         * <code>STRING = 1;</code>
         */
        public static final int STRING_VALUE = 1;
        /**
         * <code>NUMERIC = 2;</code>
         */
        public static final int NUMERIC_VALUE = 2;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static ValueType valueOf(int value) {
          return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static ValueType forNumber(int value) {
          switch (value) {
            case 0: return BOOLEAN;
            case 1: return STRING;
            case 2: return NUMERIC;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ValueType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            ValueType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<ValueType>() {
                public ValueType findValueByNumber(int number) {
                  return ValueType.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
          }
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return FeatureResponseOuterProto.FeatureResponse.Feature.getDescriptor().getEnumTypes().get(0);
        }

        private static final ValueType[] VALUES = values();

        public static ValueType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private ValueType(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:FeatureResponse.Feature.ValueType)
      }

      private int valueCase_ = 0;
      private java.lang.Object value_;
      public enum ValueCase
          implements com.google.protobuf.Internal.EnumLite,
              com.google.protobuf.AbstractMessage.InternalOneOfEnum {
        BOOLEANVALUE(2),
        STRINGVALUE(3),
        NUMERICVALUE(4),
        VALUE_NOT_SET(0);
        private final int value;
        private ValueCase(int value) {
          this.value = value;
        }
        /**
         * @param value The number of the enum to look for.
         * @return The enum associated with the given number.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static ValueCase valueOf(int value) {
          return forNumber(value);
        }

        public static ValueCase forNumber(int value) {
          switch (value) {
            case 2: return BOOLEANVALUE;
            case 3: return STRINGVALUE;
            case 4: return NUMERICVALUE;
            case 0: return VALUE_NOT_SET;
            default: return null;
          }
        }
        public int getNumber() {
          return this.value;
        }
      };

      public ValueCase
      getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public static final int VALUETYPE_FIELD_NUMBER = 1;
      private int valueType_ = 0;
      /**
       * <code>.FeatureResponse.Feature.ValueType valueType = 1;</code>
       * @return The enum numeric value on the wire for valueType.
       */
      @java.lang.Override public int getValueTypeValue() {
        return valueType_;
      }
      /**
       * <code>.FeatureResponse.Feature.ValueType valueType = 1;</code>
       * @return The valueType.
       */
      @java.lang.Override public FeatureResponseOuterProto.FeatureResponse.Feature.ValueType getValueType() {
        FeatureResponseOuterProto.FeatureResponse.Feature.ValueType result = FeatureResponseOuterProto.FeatureResponse.Feature.ValueType.forNumber(valueType_);
        return result == null ? FeatureResponseOuterProto.FeatureResponse.Feature.ValueType.UNRECOGNIZED : result;
      }

      public static final int BOOLEANVALUE_FIELD_NUMBER = 2;
      /**
       * <code>bool booleanValue = 2;</code>
       * @return Whether the booleanValue field is set.
       */
      @java.lang.Override
      public boolean hasBooleanValue() {
        return valueCase_ == 2;
      }
      /**
       * <code>bool booleanValue = 2;</code>
       * @return The booleanValue.
       */
      @java.lang.Override
      public boolean getBooleanValue() {
        if (valueCase_ == 2) {
          return (java.lang.Boolean) value_;
        }
        return false;
      }

      public static final int STRINGVALUE_FIELD_NUMBER = 3;
      /**
       * <code>string stringValue = 3;</code>
       * @return Whether the stringValue field is set.
       */
      public boolean hasStringValue() {
        return valueCase_ == 3;
      }
      /**
       * <code>string stringValue = 3;</code>
       * @return The stringValue.
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = "";
        if (valueCase_ == 3) {
          ref = value_;
        }
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 3) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>string stringValue = 3;</code>
       * @return The bytes for stringValue.
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 3) {
          ref = value_;
        }
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 3) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NUMERICVALUE_FIELD_NUMBER = 4;
      /**
       * <code>int32 numericValue = 4;</code>
       * @return Whether the numericValue field is set.
       */
      @java.lang.Override
      public boolean hasNumericValue() {
        return valueCase_ == 4;
      }
      /**
       * <code>int32 numericValue = 4;</code>
       * @return The numericValue.
       */
      @java.lang.Override
      public int getNumericValue() {
        if (valueCase_ == 4) {
          return (java.lang.Integer) value_;
        }
        return 0;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (valueType_ != FeatureResponseOuterProto.FeatureResponse.Feature.ValueType.BOOLEAN.getNumber()) {
          output.writeEnum(1, valueType_);
        }
        if (valueCase_ == 2) {
          output.writeBool(
              2, (boolean)((java.lang.Boolean) value_));
        }
        if (valueCase_ == 3) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value_);
        }
        if (valueCase_ == 4) {
          output.writeInt32(
              4, (int)((java.lang.Integer) value_));
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (valueType_ != FeatureResponseOuterProto.FeatureResponse.Feature.ValueType.BOOLEAN.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, valueType_);
        }
        if (valueCase_ == 2) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(
                2, (boolean)((java.lang.Boolean) value_));
        }
        if (valueCase_ == 3) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value_);
        }
        if (valueCase_ == 4) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(
                4, (int)((java.lang.Integer) value_));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof FeatureResponseOuterProto.FeatureResponse.Feature)) {
          return super.equals(obj);
        }
        FeatureResponseOuterProto.FeatureResponse.Feature other = (FeatureResponseOuterProto.FeatureResponse.Feature) obj;

        if (valueType_ != other.valueType_) return false;
        if (!getValueCase().equals(other.getValueCase())) return false;
        switch (valueCase_) {
          case 2:
            if (getBooleanValue()
                != other.getBooleanValue()) return false;
            break;
          case 3:
            if (!getStringValue()
                .equals(other.getStringValue())) return false;
            break;
          case 4:
            if (getNumericValue()
                != other.getNumericValue()) return false;
            break;
          case 0:
          default:
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + VALUETYPE_FIELD_NUMBER;
        hash = (53 * hash) + valueType_;
        switch (valueCase_) {
          case 2:
            hash = (37 * hash) + BOOLEANVALUE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getBooleanValue());
            break;
          case 3:
            hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
            hash = (53 * hash) + getStringValue().hashCode();
            break;
          case 4:
            hash = (37 * hash) + NUMERICVALUE_FIELD_NUMBER;
            hash = (53 * hash) + getNumericValue();
            break;
          case 0:
          default:
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static FeatureResponseOuterProto.FeatureResponse.Feature parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static FeatureResponseOuterProto.FeatureResponse.Feature parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static FeatureResponseOuterProto.FeatureResponse.Feature parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static FeatureResponseOuterProto.FeatureResponse.Feature parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static FeatureResponseOuterProto.FeatureResponse.Feature parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static FeatureResponseOuterProto.FeatureResponse.Feature parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static FeatureResponseOuterProto.FeatureResponse.Feature parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static FeatureResponseOuterProto.FeatureResponse.Feature parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static FeatureResponseOuterProto.FeatureResponse.Feature parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static FeatureResponseOuterProto.FeatureResponse.Feature parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static FeatureResponseOuterProto.FeatureResponse.Feature parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static FeatureResponseOuterProto.FeatureResponse.Feature parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(FeatureResponseOuterProto.FeatureResponse.Feature prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code FeatureResponse.Feature}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:FeatureResponse.Feature)
          FeatureResponseOuterProto.FeatureResponse.FeatureOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return FeatureResponseOuterProto.internal_static_FeatureResponse_Feature_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return FeatureResponseOuterProto.internal_static_FeatureResponse_Feature_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  FeatureResponseOuterProto.FeatureResponse.Feature.class, FeatureResponseOuterProto.FeatureResponse.Feature.Builder.class);
        }

        // Construct using FeatureResponseOuterProto.FeatureResponse.Feature.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          valueType_ = 0;
          valueCase_ = 0;
          value_ = null;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return FeatureResponseOuterProto.internal_static_FeatureResponse_Feature_descriptor;
        }

        @java.lang.Override
        public FeatureResponseOuterProto.FeatureResponse.Feature getDefaultInstanceForType() {
          return FeatureResponseOuterProto.FeatureResponse.Feature.getDefaultInstance();
        }

        @java.lang.Override
        public FeatureResponseOuterProto.FeatureResponse.Feature build() {
          FeatureResponseOuterProto.FeatureResponse.Feature result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public FeatureResponseOuterProto.FeatureResponse.Feature buildPartial() {
          FeatureResponseOuterProto.FeatureResponse.Feature result = new FeatureResponseOuterProto.FeatureResponse.Feature(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          buildPartialOneofs(result);
          onBuilt();
          return result;
        }

        private void buildPartial0(FeatureResponseOuterProto.FeatureResponse.Feature result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.valueType_ = valueType_;
          }
        }

        private void buildPartialOneofs(FeatureResponseOuterProto.FeatureResponse.Feature result) {
          result.valueCase_ = valueCase_;
          result.value_ = this.value_;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof FeatureResponseOuterProto.FeatureResponse.Feature) {
            return mergeFrom((FeatureResponseOuterProto.FeatureResponse.Feature)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(FeatureResponseOuterProto.FeatureResponse.Feature other) {
          if (other == FeatureResponseOuterProto.FeatureResponse.Feature.getDefaultInstance()) return this;
          if (other.valueType_ != 0) {
            setValueTypeValue(other.getValueTypeValue());
          }
          switch (other.getValueCase()) {
            case BOOLEANVALUE: {
              setBooleanValue(other.getBooleanValue());
              break;
            }
            case STRINGVALUE: {
              valueCase_ = 3;
              value_ = other.value_;
              onChanged();
              break;
            }
            case NUMERICVALUE: {
              setNumericValue(other.getNumericValue());
              break;
            }
            case VALUE_NOT_SET: {
              break;
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  valueType_ = input.readEnum();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                case 16: {
                  value_ = input.readBool();
                  valueCase_ = 2;
                  break;
                } // case 16
                case 26: {
                  java.lang.String s = input.readStringRequireUtf8();
                  valueCase_ = 3;
                  value_ = s;
                  break;
                } // case 26
                case 32: {
                  value_ = input.readInt32();
                  valueCase_ = 4;
                  break;
                } // case 32
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int valueCase_ = 0;
        private java.lang.Object value_;
        public ValueCase
            getValueCase() {
          return ValueCase.forNumber(
              valueCase_);
        }

        public Builder clearValue() {
          valueCase_ = 0;
          value_ = null;
          onChanged();
          return this;
        }

        private int bitField0_;

        private int valueType_ = 0;
        /**
         * <code>.FeatureResponse.Feature.ValueType valueType = 1;</code>
         * @return The enum numeric value on the wire for valueType.
         */
        @java.lang.Override public int getValueTypeValue() {
          return valueType_;
        }
        /**
         * <code>.FeatureResponse.Feature.ValueType valueType = 1;</code>
         * @param value The enum numeric value on the wire for valueType to set.
         * @return This builder for chaining.
         */
        public Builder setValueTypeValue(int value) {
          valueType_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.FeatureResponse.Feature.ValueType valueType = 1;</code>
         * @return The valueType.
         */
        @java.lang.Override
        public FeatureResponseOuterProto.FeatureResponse.Feature.ValueType getValueType() {
          FeatureResponseOuterProto.FeatureResponse.Feature.ValueType result = FeatureResponseOuterProto.FeatureResponse.Feature.ValueType.forNumber(valueType_);
          return result == null ? FeatureResponseOuterProto.FeatureResponse.Feature.ValueType.UNRECOGNIZED : result;
        }
        /**
         * <code>.FeatureResponse.Feature.ValueType valueType = 1;</code>
         * @param value The valueType to set.
         * @return This builder for chaining.
         */
        public Builder setValueType(FeatureResponseOuterProto.FeatureResponse.Feature.ValueType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          valueType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.FeatureResponse.Feature.ValueType valueType = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearValueType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          valueType_ = 0;
          onChanged();
          return this;
        }

        /**
         * <code>bool booleanValue = 2;</code>
         * @return Whether the booleanValue field is set.
         */
        public boolean hasBooleanValue() {
          return valueCase_ == 2;
        }
        /**
         * <code>bool booleanValue = 2;</code>
         * @return The booleanValue.
         */
        public boolean getBooleanValue() {
          if (valueCase_ == 2) {
            return (java.lang.Boolean) value_;
          }
          return false;
        }
        /**
         * <code>bool booleanValue = 2;</code>
         * @param value The booleanValue to set.
         * @return This builder for chaining.
         */
        public Builder setBooleanValue(boolean value) {
          
          valueCase_ = 2;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bool booleanValue = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearBooleanValue() {
          if (valueCase_ == 2) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>string stringValue = 3;</code>
         * @return Whether the stringValue field is set.
         */
        @java.lang.Override
        public boolean hasStringValue() {
          return valueCase_ == 3;
        }
        /**
         * <code>string stringValue = 3;</code>
         * @return The stringValue.
         */
        @java.lang.Override
        public java.lang.String getStringValue() {
          java.lang.Object ref = "";
          if (valueCase_ == 3) {
            ref = value_;
          }
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (valueCase_ == 3) {
              value_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string stringValue = 3;</code>
         * @return The bytes for stringValue.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
            getStringValueBytes() {
          java.lang.Object ref = "";
          if (valueCase_ == 3) {
            ref = value_;
          }
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            if (valueCase_ == 3) {
              value_ = b;
            }
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string stringValue = 3;</code>
         * @param value The stringValue to set.
         * @return This builder for chaining.
         */
        public Builder setStringValue(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          valueCase_ = 3;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string stringValue = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearStringValue() {
          if (valueCase_ == 3) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }
        /**
         * <code>string stringValue = 3;</code>
         * @param value The bytes for stringValue to set.
         * @return This builder for chaining.
         */
        public Builder setStringValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          valueCase_ = 3;
          value_ = value;
          onChanged();
          return this;
        }

        /**
         * <code>int32 numericValue = 4;</code>
         * @return Whether the numericValue field is set.
         */
        public boolean hasNumericValue() {
          return valueCase_ == 4;
        }
        /**
         * <code>int32 numericValue = 4;</code>
         * @return The numericValue.
         */
        public int getNumericValue() {
          if (valueCase_ == 4) {
            return (java.lang.Integer) value_;
          }
          return 0;
        }
        /**
         * <code>int32 numericValue = 4;</code>
         * @param value The numericValue to set.
         * @return This builder for chaining.
         */
        public Builder setNumericValue(int value) {
          
          valueCase_ = 4;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 numericValue = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearNumericValue() {
          if (valueCase_ == 4) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:FeatureResponse.Feature)
      }

      // @@protoc_insertion_point(class_scope:FeatureResponse.Feature)
      private static final FeatureResponseOuterProto.FeatureResponse.Feature DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new FeatureResponseOuterProto.FeatureResponse.Feature();
      }

      public static FeatureResponseOuterProto.FeatureResponse.Feature getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Feature>
          PARSER = new com.google.protobuf.AbstractParser<Feature>() {
        @java.lang.Override
        public Feature parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Feature> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Feature> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public FeatureResponseOuterProto.FeatureResponse.Feature getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int FEATURE_MAP_FIELD_NUMBER = 1;
    private static final class FeatureMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature>newDefaultInstance(
                  FeatureResponseOuterProto.internal_static_FeatureResponse_FeatureMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  FeatureResponseOuterProto.FeatureResponse.Feature.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> featureMap_;
    private com.google.protobuf.MapField<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature>
    internalGetFeatureMap() {
      if (featureMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FeatureMapDefaultEntryHolder.defaultEntry);
      }
      return featureMap_;
    }
    public int getFeatureMapCount() {
      return internalGetFeatureMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
     */
    @java.lang.Override
    public boolean containsFeatureMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetFeatureMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFeatureMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> getFeatureMap() {
      return getFeatureMapMap();
    }
    /**
     * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> getFeatureMapMap() {
      return internalGetFeatureMap().getMap();
    }
    /**
     * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
FeatureResponseOuterProto.FeatureResponse.Feature getFeatureMapOrDefault(
        java.lang.String key,
        /* nullable */
FeatureResponseOuterProto.FeatureResponse.Feature defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> map =
          internalGetFeatureMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
     */
    @java.lang.Override
    public FeatureResponseOuterProto.FeatureResponse.Feature getFeatureMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> map =
          internalGetFeatureMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetFeatureMap(),
          FeatureMapDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> entry
           : internalGetFeatureMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature>
        featureMap__ = FeatureMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, featureMap__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FeatureResponseOuterProto.FeatureResponse)) {
        return super.equals(obj);
      }
      FeatureResponseOuterProto.FeatureResponse other = (FeatureResponseOuterProto.FeatureResponse) obj;

      if (!internalGetFeatureMap().equals(
          other.internalGetFeatureMap())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetFeatureMap().getMap().isEmpty()) {
        hash = (37 * hash) + FEATURE_MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetFeatureMap().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FeatureResponseOuterProto.FeatureResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FeatureResponseOuterProto.FeatureResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FeatureResponseOuterProto.FeatureResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FeatureResponseOuterProto.FeatureResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FeatureResponseOuterProto.FeatureResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FeatureResponseOuterProto.FeatureResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FeatureResponseOuterProto.FeatureResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FeatureResponseOuterProto.FeatureResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FeatureResponseOuterProto.FeatureResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FeatureResponseOuterProto.FeatureResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FeatureResponseOuterProto.FeatureResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FeatureResponseOuterProto.FeatureResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FeatureResponseOuterProto.FeatureResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FeatureResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FeatureResponse)
        FeatureResponseOuterProto.FeatureResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FeatureResponseOuterProto.internal_static_FeatureResponse_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetFeatureMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableFeatureMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FeatureResponseOuterProto.internal_static_FeatureResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FeatureResponseOuterProto.FeatureResponse.class, FeatureResponseOuterProto.FeatureResponse.Builder.class);
      }

      // Construct using FeatureResponseOuterProto.FeatureResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableFeatureMap().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FeatureResponseOuterProto.internal_static_FeatureResponse_descriptor;
      }

      @java.lang.Override
      public FeatureResponseOuterProto.FeatureResponse getDefaultInstanceForType() {
        return FeatureResponseOuterProto.FeatureResponse.getDefaultInstance();
      }

      @java.lang.Override
      public FeatureResponseOuterProto.FeatureResponse build() {
        FeatureResponseOuterProto.FeatureResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FeatureResponseOuterProto.FeatureResponse buildPartial() {
        FeatureResponseOuterProto.FeatureResponse result = new FeatureResponseOuterProto.FeatureResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(FeatureResponseOuterProto.FeatureResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.featureMap_ = internalGetFeatureMap();
          result.featureMap_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FeatureResponseOuterProto.FeatureResponse) {
          return mergeFrom((FeatureResponseOuterProto.FeatureResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FeatureResponseOuterProto.FeatureResponse other) {
        if (other == FeatureResponseOuterProto.FeatureResponse.getDefaultInstance()) return this;
        internalGetMutableFeatureMap().mergeFrom(
            other.internalGetFeatureMap());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature>
                featureMap__ = input.readMessage(
                    FeatureMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableFeatureMap().getMutableMap().put(
                    featureMap__.getKey(), featureMap__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> featureMap_;
      private com.google.protobuf.MapField<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature>
          internalGetFeatureMap() {
        if (featureMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FeatureMapDefaultEntryHolder.defaultEntry);
        }
        return featureMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature>
          internalGetMutableFeatureMap() {
        if (featureMap_ == null) {
          featureMap_ = com.google.protobuf.MapField.newMapField(
              FeatureMapDefaultEntryHolder.defaultEntry);
        }
        if (!featureMap_.isMutable()) {
          featureMap_ = featureMap_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return featureMap_;
      }
      public int getFeatureMapCount() {
        return internalGetFeatureMap().getMap().size();
      }
      /**
       * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
       */
      @java.lang.Override
      public boolean containsFeatureMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetFeatureMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getFeatureMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> getFeatureMap() {
        return getFeatureMapMap();
      }
      /**
       * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> getFeatureMapMap() {
        return internalGetFeatureMap().getMap();
      }
      /**
       * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
FeatureResponseOuterProto.FeatureResponse.Feature getFeatureMapOrDefault(
          java.lang.String key,
          /* nullable */
FeatureResponseOuterProto.FeatureResponse.Feature defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> map =
            internalGetFeatureMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
       */
      @java.lang.Override
      public FeatureResponseOuterProto.FeatureResponse.Feature getFeatureMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> map =
            internalGetFeatureMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearFeatureMap() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableFeatureMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
       */
      public Builder removeFeatureMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableFeatureMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature>
          getMutableFeatureMap() {
        bitField0_ |= 0x00000001;
        return internalGetMutableFeatureMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
       */
      public Builder putFeatureMap(
          java.lang.String key,
          FeatureResponseOuterProto.FeatureResponse.Feature value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableFeatureMap().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, .FeatureResponse.Feature&gt; feature_map = 1;</code>
       */
      public Builder putAllFeatureMap(
          java.util.Map<java.lang.String, FeatureResponseOuterProto.FeatureResponse.Feature> values) {
        internalGetMutableFeatureMap().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FeatureResponse)
    }

    // @@protoc_insertion_point(class_scope:FeatureResponse)
    private static final FeatureResponseOuterProto.FeatureResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FeatureResponseOuterProto.FeatureResponse();
    }

    public static FeatureResponseOuterProto.FeatureResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeatureResponse>
        PARSER = new com.google.protobuf.AbstractParser<FeatureResponse>() {
      @java.lang.Override
      public FeatureResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FeatureResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeatureResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FeatureResponseOuterProto.FeatureResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FeatureResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FeatureResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FeatureResponse_Feature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FeatureResponse_Feature_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FeatureResponse_FeatureMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FeatureResponse_FeatureMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025featureResponse.proto\"\333\002\n\017FeatureRespo" +
      "nse\0225\n\013feature_map\030\001 \003(\0132 .FeatureRespon" +
      "se.FeatureMapEntry\032\303\001\n\007Feature\0225\n\tvalueT" +
      "ype\030\001 \001(\0162\".FeatureResponse.Feature.Valu" +
      "eType\022\026\n\014booleanValue\030\002 \001(\010H\000\022\025\n\013stringV" +
      "alue\030\003 \001(\tH\000\022\026\n\014numericValue\030\004 \001(\005H\000\"1\n\t" +
      "ValueType\022\013\n\007BOOLEAN\020\000\022\n\n\006STRING\020\001\022\013\n\007NU" +
      "MERIC\020\002B\007\n\005value\032K\n\017FeatureMapEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\'\n\005value\030\002 \001(\0132\030.FeatureRespons" +
      "e.Feature:\0028\001B\033B\031FeatureResponseOuterPro" +
      "tob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FeatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FeatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FeatureResponse_descriptor,
        new java.lang.String[] { "FeatureMap", });
    internal_static_FeatureResponse_Feature_descriptor =
      internal_static_FeatureResponse_descriptor.getNestedTypes().get(0);
    internal_static_FeatureResponse_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FeatureResponse_Feature_descriptor,
        new java.lang.String[] { "ValueType", "BooleanValue", "StringValue", "NumericValue", "Value", });
    internal_static_FeatureResponse_FeatureMapEntry_descriptor =
      internal_static_FeatureResponse_descriptor.getNestedTypes().get(1);
    internal_static_FeatureResponse_FeatureMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FeatureResponse_FeatureMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
