// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: featureRequest.proto
package org.springframework.samples.petclinic.protobuf;;

public final class FeatureRequestOuterProto {
  private FeatureRequestOuterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FeatureRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FeatureRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string features = 1;</code>
     * @return A list containing the features.
     */
    java.util.List<java.lang.String>
        getFeaturesList();
    /**
     * <code>repeated string features = 1;</code>
     * @return The count of features.
     */
    int getFeaturesCount();
    /**
     * <code>repeated string features = 1;</code>
     * @param index The index of the element to return.
     * @return The features at the given index.
     */
    java.lang.String getFeatures(int index);
    /**
     * <code>repeated string features = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the features at the given index.
     */
    com.google.protobuf.ByteString
        getFeaturesBytes(int index);
  }
  /**
   * Protobuf type {@code FeatureRequest}
   */
  public static final class FeatureRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FeatureRequest)
      FeatureRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FeatureRequest.newBuilder() to construct.
    private FeatureRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FeatureRequest() {
      features_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FeatureRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FeatureRequestOuterProto.internal_static_FeatureRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FeatureRequestOuterProto.internal_static_FeatureRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FeatureRequestOuterProto.FeatureRequest.class, FeatureRequestOuterProto.FeatureRequest.Builder.class);
    }

    public static final int FEATURES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList features_;
    /**
     * <code>repeated string features = 1;</code>
     * @return A list containing the features.
     */
    public com.google.protobuf.ProtocolStringList
        getFeaturesList() {
      return features_;
    }
    /**
     * <code>repeated string features = 1;</code>
     * @return The count of features.
     */
    public int getFeaturesCount() {
      return features_.size();
    }
    /**
     * <code>repeated string features = 1;</code>
     * @param index The index of the element to return.
     * @return The features at the given index.
     */
    public java.lang.String getFeatures(int index) {
      return features_.get(index);
    }
    /**
     * <code>repeated string features = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the features at the given index.
     */
    public com.google.protobuf.ByteString
        getFeaturesBytes(int index) {
      return features_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < features_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, features_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < features_.size(); i++) {
          dataSize += computeStringSizeNoTag(features_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFeaturesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FeatureRequestOuterProto.FeatureRequest)) {
        return super.equals(obj);
      }
      FeatureRequestOuterProto.FeatureRequest other = (FeatureRequestOuterProto.FeatureRequest) obj;

      if (!getFeaturesList()
          .equals(other.getFeaturesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFeaturesCount() > 0) {
        hash = (37 * hash) + FEATURES_FIELD_NUMBER;
        hash = (53 * hash) + getFeaturesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FeatureRequestOuterProto.FeatureRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FeatureRequestOuterProto.FeatureRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FeatureRequestOuterProto.FeatureRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FeatureRequestOuterProto.FeatureRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FeatureRequestOuterProto.FeatureRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FeatureRequestOuterProto.FeatureRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FeatureRequestOuterProto.FeatureRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FeatureRequestOuterProto.FeatureRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FeatureRequestOuterProto.FeatureRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FeatureRequestOuterProto.FeatureRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FeatureRequestOuterProto.FeatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FeatureRequestOuterProto.FeatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FeatureRequestOuterProto.FeatureRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FeatureRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FeatureRequest)
        FeatureRequestOuterProto.FeatureRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FeatureRequestOuterProto.internal_static_FeatureRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FeatureRequestOuterProto.internal_static_FeatureRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FeatureRequestOuterProto.FeatureRequest.class, FeatureRequestOuterProto.FeatureRequest.Builder.class);
      }

      // Construct using FeatureRequestOuterProto.FeatureRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        features_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FeatureRequestOuterProto.internal_static_FeatureRequest_descriptor;
      }

      @java.lang.Override
      public FeatureRequestOuterProto.FeatureRequest getDefaultInstanceForType() {
        return FeatureRequestOuterProto.FeatureRequest.getDefaultInstance();
      }

      @java.lang.Override
      public FeatureRequestOuterProto.FeatureRequest build() {
        FeatureRequestOuterProto.FeatureRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FeatureRequestOuterProto.FeatureRequest buildPartial() {
        FeatureRequestOuterProto.FeatureRequest result = new FeatureRequestOuterProto.FeatureRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(FeatureRequestOuterProto.FeatureRequest result) {
        if (((bitField0_ & 0x00000001) != 0)) {
          features_ = features_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.features_ = features_;
      }

      private void buildPartial0(FeatureRequestOuterProto.FeatureRequest result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FeatureRequestOuterProto.FeatureRequest) {
          return mergeFrom((FeatureRequestOuterProto.FeatureRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FeatureRequestOuterProto.FeatureRequest other) {
        if (other == FeatureRequestOuterProto.FeatureRequest.getDefaultInstance()) return this;
        if (!other.features_.isEmpty()) {
          if (features_.isEmpty()) {
            features_ = other.features_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFeaturesIsMutable();
            features_.addAll(other.features_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureFeaturesIsMutable();
                features_.add(s);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList features_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFeaturesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          features_ = new com.google.protobuf.LazyStringArrayList(features_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string features = 1;</code>
       * @return A list containing the features.
       */
      public com.google.protobuf.ProtocolStringList
          getFeaturesList() {
        return features_.getUnmodifiableView();
      }
      /**
       * <code>repeated string features = 1;</code>
       * @return The count of features.
       */
      public int getFeaturesCount() {
        return features_.size();
      }
      /**
       * <code>repeated string features = 1;</code>
       * @param index The index of the element to return.
       * @return The features at the given index.
       */
      public java.lang.String getFeatures(int index) {
        return features_.get(index);
      }
      /**
       * <code>repeated string features = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the features at the given index.
       */
      public com.google.protobuf.ByteString
          getFeaturesBytes(int index) {
        return features_.getByteString(index);
      }
      /**
       * <code>repeated string features = 1;</code>
       * @param index The index to set the value at.
       * @param value The features to set.
       * @return This builder for chaining.
       */
      public Builder setFeatures(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureFeaturesIsMutable();
        features_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string features = 1;</code>
       * @param value The features to add.
       * @return This builder for chaining.
       */
      public Builder addFeatures(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureFeaturesIsMutable();
        features_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string features = 1;</code>
       * @param values The features to add.
       * @return This builder for chaining.
       */
      public Builder addAllFeatures(
          java.lang.Iterable<java.lang.String> values) {
        ensureFeaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, features_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string features = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFeatures() {
        features_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string features = 1;</code>
       * @param value The bytes of the features to add.
       * @return This builder for chaining.
       */
      public Builder addFeaturesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureFeaturesIsMutable();
        features_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FeatureRequest)
    }

    // @@protoc_insertion_point(class_scope:FeatureRequest)
    private static final FeatureRequestOuterProto.FeatureRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FeatureRequestOuterProto.FeatureRequest();
    }

    public static FeatureRequestOuterProto.FeatureRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeatureRequest>
        PARSER = new com.google.protobuf.AbstractParser<FeatureRequest>() {
      @java.lang.Override
      public FeatureRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FeatureRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeatureRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FeatureRequestOuterProto.FeatureRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FeatureRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FeatureRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024featureRequest.proto\"\"\n\016FeatureRequest" +
      "\022\020\n\010features\030\001 \003(\tB\032B\030FeatureRequestOute" +
      "rProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FeatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FeatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FeatureRequest_descriptor,
        new java.lang.String[] { "Features", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
